[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
nix = { version = "0.29.0", features = ["fs", "process", "mman", "socket", "net", "signal"]}
strum = "0.27.1"
strum_macros = "0.27.1"
